import { TbMath } from "react-icons/tb";
import { MdOutlineWorkHistory } from "react-icons/md";
  const subjects = [
    {
      id: 1,
      name: "Matematica AE",
      text: "IB",
      whatsapp: "+54 9 11 3947-8794",
      icon: <TbMath size="2em" />,
    },
    {
      id: 2,
      name: "Matematica AI",
      text: "IB",
      whatsapp: "+54 9 11 3238-7146",
      icon: <TbMath size="2em" />,
    },
    {
      id: 3,
      name: "Historia",
      text: "IB",
      whatsapp: "+54 9 11  3142-2725",
      icon: <MdOutlineWorkHistory size="2em" />,
    },
    {
      id: 4,
      name: "TOK",
      text: "IB",
      whatsapp: "+54 9 11  3142-2725",
      icon: <TbMath size="2em" />,
    },
    {
      id: 5,
      name: "Economía",
      text: "IB",
      whatsapp: "+54 9 11  4493-4427",
      icon: <TbMath size="2em" />,
    },
    {
      id: 6,
      name: "Biología",
      text: "IB",
      whatsapp: "+54 9 11  4047-0174",
      icon: <TbMath size="2em" />,
    },
    {
      id: 7,
      name: "Sist. ambientales",
      text: "IB",
      whatsapp: "+54 9 11  4047-0174",
      icon: <TbMath size="2em" />,
    },
    {
      id: 8,
      name: "Gestión empresarial",
      text: "IB",
      whatsapp: "+54 9 11  3483-7506",
      icon: <TbMath size="2em" />,
    },
    {
      id: 9,
      name: "Química",
      text: "IB",
      whatsapp: "+54 9 11  6572-5768",
      icon: <TbMath size="2em" />,
    },
    {
      id: 10,
      name: "Física",
      text: "IB",
      whatsapp: "+54 9 11  3640-5029",
      icon: <TbMath size="2em" />,
    },
    {
      id: 11,
      name: "Cs. Del Deporte",
      text: "IB",
      whatsapp: "+54 9 11  5939-1165",
      icon: <TbMath size="2em" />,
    },
    {
      id: 12,
      name: "Inglés",
      text: "IB",
      whatsapp: "+54 9 11  4915-7551",
      icon: <TbMath size="2em" />,
    },
    {
      id: 13,
      name: "Español",
      text: "IB",
      whatsapp: "+54 9 11  6004-0462",
      icon: <TbMath size="2em" />,
    },
    {
      id: 14,
      name: "Francés",
      text: "IB",
      whatsapp: "+54 9 11  2714-1669",
      icon: <TbMath size="2em" />,
    },
    {
      id: 15,
      name: "Arte",
      text: "IB",
      whatsapp: "",
      icon: <TbMath size="2em" />,
    },
    {
      id: 16,
      name: "Monografía",
      text: "IB",
      whatsapp: "",
      icon: <TbMath size="2em" />,
    },
  ];

export default subjects;